[#109] Created page template story in Storybook.
civictheme/uikit pull request #119
Opened 2024-03-26 03:45 UTC by joshua-salsadigital

Closes https://github.com/civictheme/uikit/issues/109

## Checklist before requesting a review

- [ ] I have formatted the subject to include the issue number
  as `[#123] Verb in past tense with a period at the end.`
- [ ] I have provided information in the `Changed` section about WHY something was
  done if this was a bespoke implementation.
- [ ] I have performed a self-review of my code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have run new and existing relevant tests locally with my changes,
  and they have passed.
- [ ] I have provided screenshots, where applicable.

## Changed

1.

## Screenshots

2024-03-28 02:24 UTC, AlexSkrypnyk requested changes
@joshua-salsadigital 
This looks great.

however, the exposed controls need to be done a bit different: we want to expose only Organism-level controls with a minimum of options - for now, just the `Theme`. Please remove other controls.

The Knobs panel should have `General` + Tabs for each Organism used.

2024-04-11 00:41 UTC, AlexSkrypnyk requested changes
@joshua-salsadigital 
Thank you for putting through the updates.
I've reviewed it and the Storybook itself is extremely slow.

Can we please remove all of the props except for `Theme`: the theme should be passed to all component's props to have all of the changed. The rest of component's props should default to the defaults found in their stories.

2024-04-11 04:12 UTC, joshua-salsadigital commented
> @joshua-salsadigital Thank you for putting through the updates. I've reviewed it and the Storybook itself is extremely slow.
> 
> Can we please remove all of the props except for `Theme`: the theme should be passed to all component's props to have all of the changed. The rest of component's props should default to the defaults found in their stories.

Updated code, to pass default values for components, and pass theme value to components.

2024-04-18 05:43 UTC, joshua-salsadigital commented on components/04-templates/page/page.stories.js
> +  generalKnobs.logo = Logo('Logo', false, false, theme);
Refactored possible component's stories to allow a reuse of their stories without the need to expose all those additional controls.

2024-04-18 06:36 UTC, joshua-salsadigital commented on components/04-templates/page/page.stories.js
> +  generalKnobs.list_navigation = List('List', false, theme, 'navigation-card');
Note, since now we are using the default. it will be listing with filters pagination.

2024-05-07 07:56 UTC, AlexSkrypnyk requested changes
@joshua-salsadigital 
Can we please replace all these added parameters with a `defaults` object. Then, the caller can simply pass the desired defaults.

2024-06-06 12:42 UTC, AlexSkrypnyk commented
Closed in favour of https://github.com/civictheme/uikit/pull/191

2024-06-06 12:42 UTC, closed without merging