[#132] Added Layout Grid component
civictheme/uikit pull request #133
Opened 2024-04-09 18:01 UTC by joshua-salsadigital

Closes https://github.com/civictheme/uikit/issues/132

## Checklist before requesting a review

- [ ] I have formatted the subject to include the issue number
  as `[#123] Verb in past tense with a period at the end.`
- [ ] I have provided information in the `Changed` section about WHY something was
  done if this was a bespoke implementation.
- [ ] I have performed a self-review of my code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have run new and existing relevant tests locally with my changes,
  and they have passed.
- [ ] I have provided screenshots, where applicable.

## Changed

1.

## Screenshots

2024-04-11 22:11 UTC, AlexSkrypnyk commented on components/00-base/mixins/_cssgrid.scss
> +// CSSGrid system taken from: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout
Please remove this and the line below as the code below replicates the the example on MDN site rather than uses a ready-to-go code directly.

2024-04-11 22:12 UTC, AlexSkrypnyk commented on components/00-base/mixins/_cssgrid.scss
> +  // Validate $cols parameter
please remove this comment - the code already explains this intent

also, plese reverse this condition to check and exit early.

2024-04-11 22:13 UTC, AlexSkrypnyk commented on components/00-base/layout-grid/layout-grid.twig
> + * - grid_structure: [array] Grid: light, dark.
please provide a matrix-like example here in code so it is clear on how to use it

2024-04-11 22:14 UTC, AlexSkrypnyk commented on components/00-base/layout-grid/layout-grid.twig
> + * - content_mapping: [array] Map.
`map`

2024-04-11 22:14 UTC, AlexSkrypnyk commented on components/00-base/layout-grid/layout-grid.twig
> + * - grid_structure: [array] Grid: light, dark.
`grid`

2024-04-11 22:15 UTC, AlexSkrypnyk commented on components/00-base/layout-grid/layout-grid.stories.scss
> +  // Column.
Looks like this is a debug statement. please use `@todo Debug only` to spot places like this.

2024-04-11 22:15 UTC, AlexSkrypnyk commented on components/00-base/layout-grid/layout-grid.stories.js
> +    grid_structure: grid,
this is probably unfinished - please update to use textarea for the prop

2024-04-11 22:17 UTC, AlexSkrypnyk commented on components/00-base/cssgrid/_index.scss
> +.cssgrid {
`.ct-cssgrid`

2024-04-11 22:18 UTC, AlexSkrypnyk commented on components/00-base/cssgrid/_index.scss
> +  @include ct-cssgrid-col();
could you please confirm that `.col` classes produced by the generator for `CSSGrid` will not conflict with `.col` classes produced by the `Grid` generator (`container` class as a parent).

2024-04-11 22:19 UTC, AlexSkrypnyk commented on components/00-base/cssgrid/cssgrid.stories.js
> +<div class="example-container">
this example should replicate the example of the `Grid` component: columns, offsets, nested grid etc.

2024-04-11 22:19 UTC, AlexSkrypnyk requested changes
Please see inline comment

2024-04-18 07:41 UTC, joshua-salsadigital commented on components/00-base/cssgrid/_index.scss
> +  @include ct-cssgrid-col();
Updated logic, All classes are generated for 12 cols and 5 rows. 
Need a way to calcuate offset. 
ie: col-3 col-off-3 
so that it starts from 3 and ends at 6

2024-04-22 03:15 UTC, joshua-salsadigital commented on components/00-base/mixins/_cssgrid.scss
> +      .ct-cssgrid-col-offset-#{$col} {
@AlexSkrypnyk Can you review and suggest. 
how to tackle offset. 

ie: start from offset 4 but for 2 column
so tht it starts from 4 and ends at 6 


or may be 
something like. 

ct-cssgrid-col-4 
then start is 1 and end is 4 
but if 
.ct-cssgrid-col-offset-4-2
the its 
start 4 and end (4+2) 6

2024-06-04 03:08 UTC, closed without merging