[#336] H2s are displaying twice in Table of contents (TOC)
civictheme/uikit pull request #339
Opened 2024-08-01 11:58 UTC by joshua-salsadigital

Closes https://github.com/civictheme/uikit/issues/336
## Checklist before requesting a review

- [ ] I have formatted the subject to include the issue number
  as `[#123] Verb in past tense with a period at the end.`
- [ ] I have provided information in the `Changed` section about WHY something was
  done if this was a bespoke implementation.
- [ ] I have performed a self-review of my code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have run new and existing relevant tests locally with my changes,
  and they have passed.
- [ ] I have provided screenshots, where applicable.

## Changed

1. Added a check to  remove duplicates when `data-table-of-contents-anchor-scope-selector` may have duplicated clases

## Screenshots

2024-08-01 12:01 UTC, joshua-salsadigital commented on components/02-molecules/table-of-contents/table-of-contents.js
> +      // Skip adding the link if the URL already exists.
![Screenshot 2024-08-01 at 5 22 10 PM](https://github.com/user-attachments/assets/44fd1fff-78c0-4db4-b3fb-fef9dda770cb)

when scopeSelector class is duplicated on the content the loop runs twice. 

Drupal behaviours is working correctly

2024-09-04 06:24 UTC, richardgaunt commented on components/02-molecules/table-of-contents/table-of-contents.js
> +      // Skip adding the link if the URL already exists.
Thanks @joshua-salsadigital - apologies for not reviewing sooner.

2024-09-04 07:34 UTC, richardgaunt commented on components/02-molecules/table-of-contents/table-of-contents.js
> +        while (elScope.querySelectorAll(`#${anchorId}`).length || existingUrls.has(`#${anchorId}`)) {
My reading of this and perhaps I cant see it:
The problem:
- we have `.ct-layout__main` twice, one nesting another, because we are adding the h2 tags twice

The fix from what I see is we now have a set to ensure anchor is only added once **but** it looks to me at line:80 that **if an anchor already exists we generate another one with a random string.**

Question:
Given that if the url exists we generate another how are we avoiding duplicates?

2024-09-04 07:34 UTC, richardgaunt requested changes
@joshua-salsadigital Some questions

2024-09-04 09:34 UTC, joshua-salsadigital commented on components/02-molecules/table-of-contents/table-of-contents.js
> +        while (elScope.querySelectorAll(`#${anchorId}`).length || existingUrls.has(`#${anchorId}`)) {
a list is maintained of the url anchors in https://github.com/civictheme/uikit/pull/339
and on line 80 we checking across that list to avoid adding duplicate links.

2024-09-04 09:55 UTC, richardgaunt commented on components/02-molecules/table-of-contents/table-of-contents.js
> +        while (elScope.querySelectorAll(`#${anchorId}`).length || existingUrls.has(`#${anchorId}`)) {
Yes I can see at line:67 we have existingUrls but I can also see what we push to existingUrls are the random string generated anchorUrls - correct?

2024-09-04 10:11 UTC, joshua-salsadigital commented on components/02-molecules/table-of-contents/table-of-contents.js
> +        while (elScope.querySelectorAll(`#${anchorId}`).length || existingUrls.has(`#${anchorId}`)) {
no random anchorurls is not added but the base anchor id 
https://github.com/civictheme/uikit/pull/339#discussion_r1743429889
 const url = `#${anchorId}`;
 which is then added to list existingUrls.add(url);

2024-09-04 11:46 UTC, richardgaunt commented on components/02-molecules/table-of-contents/table-of-contents.js
> +      existingUrls.add(url);
Aha thanks Josh clear now - apologies I re-read this multiple times

2024-09-04 11:51 UTC, richardgaunt approved these changes
Thanks for clearing that up

2024-09-04 11:51 UTC, merged