[3469582] Fixed Alert content type - Page visibility validation issue
civictheme/uikit pull request #346
Opened 2024-08-22 08:30 UTC by joshua-salsadigital

https://www.drupal.org/project/civictheme/issues/3469582

## Checklist before requesting a review

- [ ] I have formatted the subject to include the issue number
  as `[#123] Verb in past tense with a period at the end.`
- [ ] I have provided information in the `Changed` section about WHY something was
  done if this was a bespoke implementation.
- [ ] I have performed a self-review of my code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have run new and existing relevant tests locally with my changes,
  and they have passed.
- [ ] I have provided screenshots, where applicable.

## Changed

1. Fixed Alert content type - Page visibility validation issue
2. Replaced '<br />' with ''.

## Screenshots

2024-08-22 08:30 UTC, joshua-salsadigital commented on components/03-organisms/alert/alert.js
> +  pageVisibility = pageVisibility.replace(new RegExp('<br />', 'g'), '');
Required as JSON.parse add/converts line break to <br />

2024-08-22 08:38 UTC, joshua-salsadigital commented on components/03-organisms/alert/alert.js
> +  pageVisibility = pageVisibility.replace(/<br \/>/g, '');
Required as JSON.parse add/converts line break to

2024-08-22 08:44 UTC, joshua-salsadigital commented
Not sure if we need to add code coverage for all, as i ran it locally and see that, lot of components are not covered. 
![Screenshot 2024-08-22 at 2 14 44 PM](https://github.com/user-attachments/assets/d1286b8e-b94c-4d5e-bf21-3f7d7f943111)

2024-08-25 23:12 UTC, richardgaunt requested changes
I would prefer this handled in Drupal theme as its a case of Drupal adding `br` tags to line endings in the JSON output

2024-09-04 12:10 UTC, closed without merging