[#294] Slider issue
civictheme/uikit pull request #432
Opened 2024-11-27 05:18 UTC by febdao

Closes https://github.com/civictheme/uikit/issues/294

## Checklist before requesting a review

- [x] I have formatted the subject to include the issue number
  as `[#123] Verb in past tense with a period at the end.`
- [x] I have provided information in the `Changed` section about WHY something was
  done if this was a bespoke implementation.
- [ ] I have performed a self-review of my code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have run new and existing relevant tests locally with my changes,
  and they have passed.
- [ ] I have provided screenshots, where applicable.

## Changed

1. [x] Fixed Image stretches the Slider height because it is not vertically constrained.
2. [x] The horizontal layout does not follow grid.

## Screenshots
![Screenshot 2024-06-24 at 7 19 12 PM](https://github.com/civictheme/uikit/assets/83997348/bee9465b-cd6a-464f-a51b-8339d2779a81)
![Screenshot 2024-06-24 at 7 19 27 PM](https://github.com/civictheme/uikit/assets/83997348/5a9a38c3-74e1-4430-befd-b05468163c4d)

2024-11-28 02:44 UTC, alan-cole requested changes

2024-11-28 02:44 UTC, alan-cole commented on components/03-organisms/slider/slider.js
Are we able to add a fix in here:

```
this.rail.style.height = '';
this.panel.style.height = '';
```

This resets the rail and panel height before calculating the height of the slides.

2024-12-18 12:19 UTC, alan-cole requested changes

2024-12-18 12:19 UTC, alan-cole commented on components/03-organisms/slider/slide.twig
> +    <div class="col-xxs-12 {% if image_position == 'right' %}col-m-5 col-m-offset-1{% else %}col-m-5 col-m-offset-1{% endif %} ct-flex-align-self-center">
The logic here:

```
{% if image_position == 'right' %}
  col-m-5 col-m-offset-1
{% else %}
  col-m-5 col-m-offset-1
{% endif %}
```

It seems either way it's going to add the same classes - do we need this `if` statement?

2024-12-18 12:19 UTC, alan-cole commented on components/03-organisms/slider/slide.twig
> +		    <div class="col-xxs-12 first {% if image_position == 'right' %}col-m-5 col-m-offset-1 last-m{% else %}col-m-5 first-m{% endif %}">
In both `right` and `else` cases the `col-m-5` is added. Maybe we move that outside the if statement?

2024-12-18 12:19 UTC, alan-cole commented on components/03-organisms/slider/slide.twig
> +    <div class="col-xxs-12 {% if image_position == 'right' %}col-m-5 col-m-offset-1{% else %}col-m-5 col-m-offset-1{% endif %} ct-flex-align-self-center">
Although the grid system has been added, I can see the old system still exists in the styles, and the classes generated:

```scss
.ct-slide {
  $root: &;

  min-height: $ct-slider-slide-mobile-min-height;

  @include ct-breakpoint(m) {
    min-height: $ct-slider-slide-desktop-min-height;
    display: flex;
    flex-wrap: nowrap;
  }

  &#{$root}--image-right {
    @include ct-breakpoint(m) {
      flex-direction: row-reverse;
    }
  }
// ...
```

```twig
{% set image_position_class = image_position in ['left', 'right'] ? 'ct-slide--image-%s'|format(image_position) : 'right' %}
```

We should remove any unused CSS if we're going to be using the grid now.

2025-01-16 22:57 UTC, febdao commented on components/03-organisms/slider/slide.twig
> +		    <div class="col-xxs-12 first {% if image_position == 'right' %}col-m-5 col-m-offset-1 last-m{% else %}col-m-5 first-m{% endif %}">
@alan-cole 
I've check and update the spacing between the content elements, but with the whitespace around the content it comes from the height of slide item in a slider which bases on the min-height (` $ct-slider-slide-mobile-min-height` and `$ct-slider-slide-desktop-min-height`) and other item.

2025-01-16 23:15 UTC, febdao commented on components/03-organisms/slider/slider.scss
> +    @include ct-image-fit();
@alan-cole 
it becauses of we need the `@include ct-image-fit();` on mobile and `@include ct-image-container-square();` on desktop.

2025-01-16 23:16 UTC, febdao commented
hi @alan-cole 
Thank you for reviewing, the code has been updated!

2025-01-17 00:12 UTC, alan-cole commented on components/03-organisms/slider/slider.scss
> +    @include ct-image-fit();
Seems the only two places `ct-image-container-square` is used is here, and `campaign`, and in both cases, it calls the object-fit before the breakpoint, and then this in the breakpoint.

Feels like maybe this should be handled differently (a way to provide a breakpoint into container-square, or a way to disable calling image-fit within container-square). But either way it's probably not a solution that needs to be solved in this ticket.

2025-01-17 00:13 UTC, alan-cole approved these changes

2025-01-20 03:36 UTC, richardgaunt approved these changes

2025-01-20 03:36 UTC, merged