[#378] Fixed error message with screen reader.
civictheme/uikit pull request #439
Opened 2024-12-01 12:31 UTC by febdao

Fixed: https://github.com/civictheme/uikit/issues/378

## Jira ticket:
- https://salsadigital.atlassian.net/browse/CIVIC-1990

## Checklist before requesting a review

- [ ] I have formatted the subject to include the issue number
  as `[#123] Verb in past tense with a period at the end.`
- [ ] I have provided information in the `Changed` section about WHY something was
  done if this was a bespoke implementation.
- [ ] I have performed a self-review of my code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have run new and existing relevant tests locally with my changes,
  and they have passed.
- [ ] I have provided screenshots, where applicable.

## Changed

1. Add the aria-describedby attribute to all inputs that may require an error message. 
2. When an input is in an error state, inject the error container with an error message. 
3. Add the aria-invalid attribute to all required fields with a value of "false". Update this to "true" when the input is in an error state.

## Screenshots

![Screenshot 2024-12-01 at 11 23 16 pm](https://github.com/user-attachments/assets/e9220c12-b9b1-411a-80aa-d6de92066fa8)
![Screenshot 2024-12-01 at 11 22 41 pm](https://github.com/user-attachments/assets/dacaf531-50d1-451b-94f2-3ff6631251e5)

2024-12-16 02:58 UTC, richardgaunt commented on components/01-atoms/checkbox/checkbox.twig
> +		{% if is_invalid and id %}aria-describedby="{{ id }}-message"{% endif %}
Does this work with Drupal?

2024-12-16 02:58 UTC, richardgaunt commented on components/01-atoms/checkbox/checkbox.twig
> +		{% if is_invalid and id %}aria-describedby="{{ id }}-message"{% endif %}
ie seems like we would need to pass the ID of the message block at the top of the screen

2024-12-16 03:00 UTC, richardgaunt commented on components/01-atoms/field-message/__snapshots__/field-message.test.js.snap
> +    id=""
We should never have an empty id

2024-12-16 03:14 UTC, richardgaunt commented on components/01-atoms/input/input.twig
> +		{% if is_required %}required aria-invalid="{{ is_invalid ? is_invalid : 'false' }}"{% endif %}
If it is not invalid why do we want to add this attribute?

2024-12-16 03:19 UTC, richardgaunt commented on components/01-atoms/input/input.twig
> +		{% if is_required %}required aria-invalid="{{ is_invalid ? is_invalid : 'false' }}"{% endif %}
Think this should be outside of the is_required attribute check

2024-12-16 03:20 UTC, richardgaunt commented on components/01-atoms/select/select.twig
> +		{% if is_required %}required aria-invalid="{{ is_invalid ? is_invalid : 'false' }}"{% endif %}
Same as above

2024-12-16 03:20 UTC, richardgaunt requested changes
@febdao I have some questions about the use of aria-invalid and its position within the component

2025-02-17 05:07 UTC, alan-cole commented on components/01-atoms/input/input.twig
> +		{% if is_invalid and id %}aria-describedby="{{ id }}-message"{% endif %}
We recreate this string concatenation in 6 places..

`aria-describedby="{{ id }}-message"` - if the ID needed to be changed, it would need to be updated in 6 separate components.

Maybe a better option would be `aria-describedby="{{ description_id }}"`
And we pass in the description id from the `field.twig` - that way field.twig can create the the full ID for each element and message and pass it in.

I think this would also make the `describedby` more flexible, as describedby can contain more than 1 id (space separated).

2025-02-21 00:05 UTC, febdao commented on components/01-atoms/checkbox/checkbox.twig
> +		{% if is_invalid and id %}aria-describedby="{{ id }}-message"{% endif %}
Yes @richardgaunt the ID has been there, so I think it doesn't require any update in CivicTheme

2025-02-21 00:22 UTC, febdao commented on components/01-atoms/input/input.twig
> +		{% if is_required %}required aria-invalid="{{ is_invalid ? is_invalid : 'false' }}"{% endif %}
The aria-invalid supports both `true` and `false` value.
Let me updated the position of it to outside of the `is_required`

2025-02-21 00:22 UTC, febdao commented on components/01-atoms/select/select.twig
> +		{% if is_required %}required aria-invalid="{{ is_invalid ? is_invalid : 'false' }}"{% endif %}
The aria-invalid supports both `true` and `false` value.
Let me updated the position of it to outside of the `is_required`

2025-02-21 01:18 UTC, febdao commented on components/02-molecules/field/field.twig
> +					message_id: control[0].id and type not in ['radio', 'checkbox'] ? control[0].id ~ '-message'  : null,
The checkbox and radio groups need to have a different approach for the error message, 
As the current markup of the field.twig file, I'm going to implement the method #2 base on this link https://russmaxdesign.github.io/accessible-error-fieldset/

2025-02-21 01:26 UTC, febdao commented on components/01-atoms/input/input.twig
> +		{% if is_invalid and id %}aria-describedby="{{ id }}-message"{% endif %}
hi @alan-cole 
if we create a new `description_id` variable, it means we need to update the CivicTheme to support this variable as well. Should we do it?

2025-02-21 05:09 UTC, febdao commented
The CR has been fixed but this PR is no longer required as the issue has been fixed by this PR https://github.com/civictheme/uikit/pull/480

![Screenshot 2025-02-21 at 4 09 43 pm](https://github.com/user-attachments/assets/8f909330-26a9-466a-a011-ba9ccfac78cc)

2025-02-21 05:09 UTC, closed without merging