[97] Refactored Quote component to support citation.
civictheme/uikit pull request #99
Opened 2024-03-07 12:43 UTC by joshua-salsadigital

Closes https://github.com/civictheme/uikit/issues/97

## Checklist before requesting a review

- [ ] I have formatted the subject to include the issue number
  as `[#123] Verb in past tense with a period at the end.`
- [ ] I have provided information in the `Changed` section about WHY something was
  done if this was a bespoke implementation.
- [ ] I have performed a self-review of my code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have run new and existing relevant tests locally with my changes,
  and they have passed.
- [ ] I have provided screenshots, where applicable.

## Changed

1. Refactored the Quote component to use the new structure and updated SCSS.

## Screenshots

2024-03-07 12:47 UTC, joshua-salsadigital commented
Note by default cite has italic style. 
Do we remove it to match original or keep it.

2024-03-07 16:41 UTC, joshua-salsadigital commented on components/02-molecules/quote/quote.scss
> +    font-style: normal;
To match old quote author - font-style: normal;

2024-03-07 16:42 UTC, joshua-salsadigital commented on components/02-molecules/quote/quote.scss
> +  p {
To handle CKeditor adds a p tag for content within block-quote.

2024-03-07 22:20 UTC, AlexSkrypnyk requested changes
Please see my inline comments.

Please add author to the `<blockquote>` in the `basic-content.stories.js`

2024-03-07 22:20 UTC, AlexSkrypnyk commented on components/02-molecules/quote/quote.scss
> +    font-style: normal;
@joshua-salsadigital 
why do we need `font-style: normal;`? the `ct-typography('label-small');` should fully take care of the look and feel unless this is completely custom

2024-03-07 22:20 UTC, AlexSkrypnyk commented on components/02-molecules/quote/quote.scss
>  .ct-quote {
please add `<blockquote>` at the top unless this file is imported into `content.scss` where `<blockquote>` is already present.

We need this to work on markup without classes.

2024-03-11 04:30 UTC, joshua-salsadigital commented on components/02-molecules/quote/quote.scss
> +    font-style: normal;
<img width="362" alt="Screenshot 2024-03-11 at 9 59 20 AM" src="https://github.com/civictheme/uikit/assets/83997348/6743b4e6-4744-4be8-89ed-81f89fa0a0d2">
cite tag by default has italic style. To override the style and match existing old quote author overwride is needed. 
ct-typography('label-small') does not apply font-style

2024-03-11 04:31 UTC, joshua-salsadigital commented on components/02-molecules/quote/quote.scss
>  .ct-quote {
Updated the components. 
Removed quote as it does not have classes and the creditor component to be used. 
A it will be a stand alone component in Creditor for Basic Content.

2024-03-11 21:52 UTC, AlexSkrypnyk approved these changes

2024-03-11 21:55 UTC, merged